# Site settings
title: Button Up!
header-img: assets/home-bg.jpg
email: buttonup@riseup.net
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://buttonupproject.com"
github_username:  buttonup
email_username:  buttonup@riseup.net

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
